print("hello this is from shashank's branch")
print("hello this is from sahil branch")
print("hello this is from Anuruddh's branch")
print("Hello how are you")
print("hello this is from shashank's branch")
print("hello this is from sahil branch")
print("hello this is from Anuruddh's branch")
print("Hello how are you")